name: Update README all day at 06:00

on:
  push:
  workflow_dispatch:
  schedule:
    # “At 06:00 on every day-of-week.”
    - cron: '00 06 * * *'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update README.md file
        run: |
          php index.php
        env:
          CI: true
      - name: commit changes
        uses: EndBug/add-and-commit@v4
        with:
          author_name: Raphtml
          author_email: raphael.liere@hotmail.fr
          force: false
          signoff: false
          message: ':memo: README.md automatically updated'
        env:
          # This is necessary in order to push a commit to the repo
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
